# Generated by Django 4.0.6 on 2022-11-22 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strainbrowser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreederExportValid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='strainbackup',
            name='backup_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_backup_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainbackup',
            name='backup_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='strainbackup',
            name='edited_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_backup_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
