# Generated by Django 4.0.6 on 2022-11-13 13:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strainbrowser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strainbackup',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 13, 4, 43, 182732, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strainbackup',
            name='backup_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='straintranslation',
            name='edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strain_translation_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
