# Generated by Django 4.0.6 on 2022-11-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strainbrowser', '0002_breederexportvalid_alter_strainbackup_backup_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreederExportValid',
        ),
        migrations.AlterField(
            model_name='breeder',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeder_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeder_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strain',
            name='added_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strain',
            name='edited_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainbackup',
            name='backup_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_backup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strainbackup',
            name='edited_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_backup_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='straintranslation',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_translation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='straintranslation',
            name='edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='strain_translation_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
