# Generated by Django 4.0.6 on 2022-11-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='forum_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='forum_thread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language'),
        ),
        migrations.AddField(
            model_name='thread',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='forum.forumsections'),
        ),
    ]
