# Generated by Django 3.2.12 on 2022-11-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexTextModel',
            new_name='IndexText',
        ),
    ]
