# Generated by Django 3.2.12 on 2022-11-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_indextextmodel_indextext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexText',
        ),
    ]
