# Generated by Django 4.0.6 on 2022-11-19 13:43

from django.db import migrations, models
import django.db.models.deletion
import growlog.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Growlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('flower_on', models.DateField(editable=False, null=True)),
                ('finished_on', models.DateTimeField(editable=False, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('growlog.operator', 'Growlog Operator')],
            },
        ),
        migrations.CreateModel(
            name='GrowlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowlogVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GrowlogEntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('image', models.ImageField(upload_to=growlog.functions.growlog_image_upload_path)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growlog.growlogentry')),
            ],
        ),
    ]
