# Generated by Django 4.0.6 on 2022-11-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strainbrowser', '0001_initial'),
        ('growlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growlogentryimage',
            name='strains',
            field=models.ManyToManyField(to='strainbrowser.strain'),
        ),
        migrations.AddField(
            model_name='growlogentry',
            name='growlog',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='growlog.growlog'),
        ),
        migrations.AddField(
            model_name='growlog',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language'),
        ),
        migrations.AddField(
            model_name='growlog',
            name='strains',
            field=models.ManyToManyField(to='strainbrowser.strain'),
        ),
        migrations.AddField(
            model_name='growlog',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growlog',
            name='visibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='growlog.growlogvisibility'),
        ),
    ]
