# Generated by Django 3.2.12 on 2022-11-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221102_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user|manage', 'Allowed to manage users'), ('forum|operator', 'Forum operator'), ('forum|thread_create', 'Allowed to create threads in the forum.'), ('forum|thread_post', 'Allowed to post in forums.'), ('pm|allow_all', 'Allowed to post personal messages to any member'), ('wiki|operator', 'Allowed to remove wiki entries and add new sections'), ('wiki|edit_all', 'Allowed to edit all wiki entries'), ('wiki|author', 'Allowed to create wiki-entries and edit them')]},
        ),
    ]
